### ISSUE TITLE
windows10 platform require path error

### ISSUE THREAD

**Issue by undermoodzyx** [power-assert-js/intelli-espower-loader#14]
**platform:**   windows10
**shell:**   babun or cmder
Below is my **package.json** settings.
```
{
    "name": "power_assert",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "test": "mocha -r intelli-espower-loader test/**/*.js"
    },
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "intelli-espower-loader": "^1.0.1",
        "mocha": "^3.2.0",
        "power-assert": "^1.4.2"
    }
}
```
When I run ```mocha -r intelli-espower-loader``` or ```npm test```, the shell reports
```
module.js:472  
  throw err;
    ^

Error: Cannot find module 'E:\assert\node_modules\.npminstall\intelli-espower-loader\1.0.1\package.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getPackageJSON (E:\assert\node_modules\.npminstall\intelli-espower-loader\1.0.1\intelli-espower-loader\lib\get-package-json.js:29:12)
    at Object.<anonymous> (E:\assert\node_modules\.npminstall\intelli-espower-loader\1.0.1\intelli-espower-loader\intelli-espower-loader.js:3:44)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\Users\ZYX\AppData\Roaming\npm\node_modules\.mocha_npminstall\mocha\3.1.2\mocha\bin\_mocha:344:3
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\ZYX\AppData\Roaming\npm\node_modules\.mocha_npminstall\mocha\3.1.2\mocha\bin\_mocha:343:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)

```
However, the order ```mocha -r intelli-espower-loader``` works fine in linux(ubuntu) platform.
Hope for solution to solve this problem and **thanks!**

**Comment by twada** [comment]
@undermoodzyx Thank you for reporting. I'll fix this issue but it will take a while since I do not have Windows.

**Comment by twada** [comment]
@undermoodzyx  Sorry for my late response.

Today my coleague investigated this issue and found that directory structure is different (`.npminstall` exists just under the `node_modules`) from npm's. You are be using [cnpm](https://github.com/cnpm/npminstall) isn't it?

intelli-espower-loader only supports npm (and yarn) directory structure since intelli-espower-loader traverses up directory tree to find appropriate `package.json`.

I also found that latest version of cnpm [has removed .npminstall directory](https://github.com/cnpm/npminstall/commit/0d250864d20d9e6101d5b78e52dc381d677bc04d).

Would you update your cnpm to the latest version and try again?

**Comment by undermoodzyx** [comment]
@twada 
You're right!
I'd tried doing as you said and it worked.
**Thanks!!**
