### ISSUE TITLE
Not working with Node.js v8

### ISSUE THREAD

**Issue by leedm777** [power-assert-js/intelli-espower-loader#16]
I'm not seeing power-assert goodness when using Node.js v8. Using the example in [the example directory](https://github.com/power-assert-js/intelli-espower-loader/tree/master/example):

```shell
$ node --version
v8.0.0

$ npm install --silent
<snip/>

$ npm test

> example@1.0.0 test /Users/dlee/tmp/intelli-espower-loader/example
> mocha



  FailTest
    1) is failed

  PassTest
    ✓ is passed


  1 passing (33ms)
  1 failing

  1) FailTest is failed:

      AssertionError [ERR_ASSERTION]: { name: 'Tom object' } deepEqual { name: 'Mom object' }
      + expected - actual

       {
      -  "name": "Tom object"
      +  "name": "Mom object"
       }
      
      at Decorator.concreteAssert (node_modules/empower/lib/decorator.js:61:21)
      at Function.decoratedAssert [as deepEqual] (node_modules/empower/lib/decorate.js:44:26)
      at Context.<anonymous> (test/fail-test.js:9:16)
```

I should have seen the super-awesome:
```
  assert.deepEqual(object, { name: "Mom object" })
                   |       |                      
                   |       Object{name:"Mom object"}
                   Object{name:"Tom object"}      
```

**Comment by twada** [comment]
@leedm777 Thank you for reporting.
Yes. I have to deal with Node v8.
Please stay tuned.

refs https://github.com/power-assert-js/power-assert/issues/85

**Comment by twada** [comment]
@leedm777 now fixed. Thank you for reporting!

**Comment by leedm777** [comment]
Fix confirmed! Thanks for the quick response!
